[options]
db_host = tnm.host.postgres
db_port = 5432
db_user = postgres
db_password = tnm.odoo.db.pass.postgres
db_name = universeplast
addons_path = addons
xmlrpc_port = 8069
logfile = odoo.log
admin_passwd = universeplast
language = fr_FR
